# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.0.0
maven_group = dev.tsuyumori.honig
archives_name = honig
enabled_platforms = fabric,neoforge

# Minecraft properties 1.21.1
minecraft_version = 1.21.1

# Dependencies
fabric_loader_version = 0.16.14
fabric_api_version = 0.115.5+1.21.1
neoforge_version = 21.1.145
