modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "honig"
version = "${version}"
displayName = "Honig"
authors = "Tsuyumori"
description = '''
Lightweight rendering library for NeoForge and Fabric
'''
#logoFile = ""

[[dependencies.honig]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.honig]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "honig.mixins.json"
